### ISSUE TITLE
Set up code/framewowk

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#2]
1. Chạy được code HTTP API video editor: https://github.com/superdesk/video-server

**Comment by huypq20110653** [comment]
Clone project **"HTTP API video editor"** tại link: **`https://github.com/superdesk/video-server-app`** để tìm hiểu các tính năng và viết test case.
Nhóm sử dụng `docker` để chạy.
Clone project: **`git clone https://github.com/superdesk/video-server-app.git`**
Thêm dòng lệnh **`RUN git config --global url."https://github.com".insteadOf git://github.com`** vào 
![Image](https://user-images.githubusercontent.com/126330599/226230369-06c42700-5d05-44c0-8585-c49ecf82995f.png)

Sau đó, ta thực thi dòng lệnh: **`docker-compose up -d`**

Clone và chạy project thành công => tiến hành tìm hiểu các tính năng trong project
![Image](https://user-images.githubusercontent.com/126330599/226230378-9e603b75-d864-43e0-a967-4f95a8b76199.png)
