### ISSUE TITLE
Tìm hiểu tính năng của HTTP API video editor (part 2)

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#4]
edit video:(trim, rotate, scale, crop)
capture a thumbnails for timeline
capture a thumbnail for a preview at a certain position of the video, with optional crop and rotate params

**Comment by huypq20110653** [comment]
**1. **Tạo project để demo**** 

Upload một video
![image](https://user-images.githubusercontent.com/126330599/226172774-07112f60-079c-40a0-8a3a-f85530ec9832.png)

Server response sẽ trả về id của video do api tạo ra  
![image](https://user-images.githubusercontent.com/126330599/226172822-0d5a588c-8afa-48bc-a9c2-53b364abfcd6.png)

**2. **Edit project's video****

Dán địa chỉ id của video ta nhận được từ response server vào textbox và edit value cho các key "crop", "rotate", "scale", "trim". Sau đó, ta bấm "Execute".
![image](https://user-images.githubusercontent.com/126330599/226172849-fa850972-c9f3-41ea-a7f4-dc69802bacbf.png)

Response trả về bảo rằng Video không thể chỉnh sửa, yêu cầu ta duplicate video. 
![image](https://user-images.githubusercontent.com/126330599/226172911-9bb72866-b9e7-48b8-b121-91ee869dd332.png)

Ta dán id của video vào textbox và bấm "Execute"
![image](https://user-images.githubusercontent.com/126330599/226172937-3ac62ba5-f5e9-4e95-89b9-5190a6758cc2.png)

Server response sẽ trả về cho ta một địa chỉ id mới
![image](https://user-images.githubusercontent.com/126330599/226173004-db87e652-803c-473c-ad8c-907a7a4b7c9a.png)

Response sẽ thông báo rằng Video ta đã duplicate thành công
![Image](https://user-images.githubusercontent.com/126330599/226173386-e04a9410-caf1-4213-af0a-c1a13d213cc4.png)

Ta dán lại địa chỉ id mới vào ô textbox của edit video:
![image](https://user-images.githubusercontent.com/126330599/226173049-0cd0d79a-1199-4d6f-8191-207260630056.png)

Server response sẽ trả về thông tin rằng video đang được xử lý
![image](https://user-images.githubusercontent.com/126330599/226173079-56ea76d1-43fd-4996-862b-541b37726574.png)

Quá trình edit video đã khởi động thành công
![Image](https://user-images.githubusercontent.com/126330599/226173497-114c432d-1556-40c0-acee-60c81383466f.png)
