### ISSUE TITLE
Tìm hiểu tính năng của HTTP API video editor(part 3)

### ISSUE THREAD

**Issue by bngoc1307** [bngoc1307/Nhom04_CCPTPM#5]
# Task (only demo + documents):
## 4. Stream video

**Comment by ngvan1612** [comment]
# 1. List APIs

![](https://www.linkpicture.com/q/g-01.png)

# 2. Get thumbnails files

## 1. Đầu tiên ta tạo một project với một video trước

![](https://www.linkpicture.com/q/g-02.png)

> Ta thu được cái id do api tạo ra là **`6416c22ae533a4a07dc292bf`**

![](https://www.linkpicture.com/q/g-03.png)
